name: learn-github-actions
on: [push]
env:
  this : is
  this2 : is2

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      # - env:
      #     this : is
      #     this2 : is2
        env: 
          SUPER_SECRET: ${{ secrets.TEST }}
      - run: |
          echo "${{ env.this }} is pen ${{ env.this2 }} ${{ secret.TEST }} $SUPER_SECRET"
          echo "this is pen" | base64
      - run: |
          npm --version
          node --version