name: learn-github-actions
on: [push]
env:
  this : is
  this2 : is2
  this3 : ${{ secrets.TEST }}
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - if: github.event_name == 'push'
      #   run: echo "TEST=main >> $GITHUB_ENV"




      - run: |
          echo "${{ env.this }} is pen ${{ env.this3 }} $SUPER_SECRET"
          echo "this is pen" | base64
          echo "${{github.head_ref}}"
        env: 
          SUPER_SECRET: ${{ secrets.TEST }}
      - run: |
          npm --version
          node --version